### ISSUE TITLE
where is DetailHandler implemented?

### ISSUE THREAD

**Issue by krushnaal-pai** [amrro/firestore-android-arch-components#7]
This is not an issue. Its a question though. Let me know if I should remove this.

I would like to know that in "activity_restaurant_detail.xml" file, there are variables noReviews and handler. 
Where is noReviews set in .java file. 
Where is handler implemented? 
Which code gets executed when "@{(view) -> handler.addRating(true)}" gets called?

I found addRating methods but they dont have this signature addRating(boolean val). 

Thanks.

**Comment by amrro** [comment]
Any Question are very welcomed @krushnaal-pai 
I am using data binding library to bind values to variables declared inside the xml files.
You can read more about [here](https://developer.android.com/topic/libraries/data-binding/index.html).
